config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resources :messages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  root 'users#new'

  get 'ask_new_message', controller:'messages', action: 'ask_new_message'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
require 'obscenity/active_model'

class Message < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
  validates :content, presence: true
  validates :content, uniqueness: {scope: :user}
  validates :content,  obscenity: { sanitize: true,  message: 'Burby ti vede'  }
  default_scope -> {includes(:user).order('created_at ASC')}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  validates :name, presence: true
  validates :name,  obscenity: { sanitize: true,  message: 'Burby ti vede'  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_user
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  def ask_new_message
    @messages = Message.all
    id = @messages.last.id
    
    return head :ok if id == params[:last_message_id].to_i
    render 'replace_content', format: :js, layout: false
  end

  # GET /messages
  def index
    redirect_to '/users/new' if session[:user].blank?
    @message = Message.new
    @messages = Message.all
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # POST /messages
  def create
    @messages = Message.all
    @message = Message.new(message_params)
    @message.user = @user
    @message.save
    render format: :js, layout: false
  end

  private
  def set_user
    @user = User.find(session[:user]["id"]) if session[:user].present?
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def message_params
      params.require(:message).permit(:user_id, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user] = @user
      redirect_to messages_url
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title BurbyChat
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %meta(name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1")

  %body
    - url = url_for(action: 'ask_new_message', controller: 'messages')
    - if controller_name == "messages"
      #notifications{data:{url: url}}
    .row(style="margin: 0px 20px; position: fixed; top: 0;z-index:100; width: 100%; background-color: #fff; padding:0; margin:0; padding-top: 20px; padding-bottom: 20px; padding-right: 20px; border-bottom: 1px solid #ccc")
      
      .col-xs-8
        
        %strong 
          - if @user.present? and @user.name.present?
            = truncate @user.name
          - else
            AleBurbeTeScrivo
        
      .col-xs-4
        - if controller_name == "messages"
          .pull-right= link_to 'Esci', 'users/new'
    .container-fluid
      .row
        .col-sm-12= yield

app/views/messages/_form.html.haml
.panel.panel-default(style="position: fixed; bottom: -25px; width: inherit; padding: 0; left: 0; background-color: #eee")
  .panel-body
    = simple_form_for(@message, remote: true) do |f|
      %small.errors
      .row(style="padding-left:20px; padding-right: 20px; margin-bottom: -10px")
        .col-xs-9(style="padding:0")= f.input :content, label: false, input_html: {rows: 1}
        .col-xs-3(style="padding:0")= f.button :submit, 'Invia', class: 'btn btn-block btn-primary'

app/views/messages/_messages.haml
- messages.last(10).each do |message|  
  - style = "margin-bottom: 1px;"
  - if message.user.present? and message.user.id == session[:user]["id"].to_i
    - style += "background-color: #efefef" 
    
  .message{data: {id:message.id}}
    .panel.panel-default{style: style}
      
      .panel-body
        - if message.user.present?
          = message.user.name 
          %em= "dice"
          %strong= message.content

app/views/messages/create.js.erb
$('.errors').html("")
$('textarea').css('border', '1px solid black')

<% if @message.errors.present? %>

  <% @message.errors.full_messages.each do |error| %>
    $('.errors').html("<div class='errore' style='margin-bottom: 2px; color: red'><%= error %></div>")
    $('textarea').css('border', '1px solid red')
  <% end %>

<% else %>
  $('#messages').html("<%= escape_javascript(render partial: 'messages', locals: { messages: Message.all } ) %>")
  $('textarea').val("")

  var checkExist = setInterval(function() {
     if ($('#messages').length) {
        clearInterval(checkExist);
        andareGiu()
     }
  }, 100);
<% end %>

app/views/messages/index.html.haml
#form(style="width: 100%")
  = render 'form'
  %tbody
    #messages
      = render 'messages', messages: @messages

%br


:css
  td {
    border: none
  }

app/views/messages/new.html.haml
%h1 New message

= render 'form'

= link_to 'Back', messages_path

app/views/messages/replace_content.js.erb
$('#messages').html("<%= escape_javascript(render partial: 'messages', locals: { messages: @messages } ) %>")
andareGiu()

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification
  = f.input :name, as: :string, label: false, placeholder: 'Scegli un nome'
  = f.button :submit, 'Entra'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
= render 'form'

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path